DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwciI6MTcyMzM3ODU4NiwidXNlcklkIjoyfQ.gSFbIGtKj7nZwwcjxL2-JNhqbLyWtbDKtCM4ewyLLuw