PUT http://localhost:8080/events/1
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHByIjoxNzIzMzc4ODg0LCJ1c2VySWQiOjF9.J5QCGb9p116KBDP6PFavDH6P80cx-AQMeLFUy5FUFK8

{
  "nAme": "Updated event",
  "description": "Updated event desc",
  "location": "New Location",
  "datetime": "2025-01-01T15:30:00.000Z"
}